### ISSUE TITLE
language_check.JavaError: can't find Java

### ISSUE THREAD

**Issue by ghost** [tahaHichri/ML-fomo#1]
Traceback (most recent call last):
  File "C:\Users\f.ksontini\AppData\Local\Programs\Python\Python37\lib\site-packages\language_check\__init__.py", line 594, in get_server_cmd
    cmd = cache['server_cmd']

C:\workplace\IA\ML-fomo>python main.py 'Metallica' 100
Traceback (most recent call last):
  File "C:\Users\f.ksontini\AppData\Local\Programs\Python\Python37\lib\site-packages\language_check\__init__.py", line 594, in get_server_cmd
    cmd = cache['server_cmd']
KeyError: 'server_cmd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\f.ksontini\AppData\Local\Programs\Python\Python37\lib\site-packages\language_check\__init__.py", line 605, in get_jar_info
    java_path, jar_path = cache['jar_info']
KeyError: 'jar_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 226, in <module>
    main()
  File "main.py", line 180, in main
    api = TwitterAnalyzer()
  File "main.py", line 52, in __init__
    self._checkLang =  language_check.LanguageTool('en-US')
  File "C:\Users\f.ksontini\AppData\Local\Programs\Python\Python37\lib\site-packages\language_check\__init__.py", line 196, in __init__
    self._start_server_on_free_port()
  File "C:\Users\f.ksontini\AppData\Local\Programs\Python\Python37\lib\site-packages\language_check\__init__.py", line 333, in _start_server_on_free_port
    cls._start_local_server()
  File "C:\Users\f.ksontini\AppData\Local\Programs\Python\Python37\lib\site-packages\language_check\__init__.py", line 345, in _start_local_server
    server_cmd = get_server_cmd(cls._port)
  File "C:\Users\f.ksontini\AppData\Local\Programs\Python\Python37\lib\site-packages\language_check\__init__.py", line 596, in get_server_cmd
    java_path, jar_path = get_jar_info()
  File "C:\Users\f.ksontini\AppData\Local\Programs\Python\Python37\lib\site-packages\language_check\__init__.py", line 609, in get_jar_info
    raise JavaError("can't find Java")
language_check.JavaError: can't find Java

**Comment by tahaHichri** [comment]
Hello fksontini,
This seems like an issue with _Java_ and _Language_check_. 
Do you happen to hava Java 6 or newer present in your environment?

Java is a prerequisite for _language_check_
Quoting the doc:
> Python 3.3+ (or 2.7)
> lib3to2 (if installing for Python 2)
> LanguageTool (Java 6.0+)

Please install Java and make sure it is added to your PATH.
Best,
